### ISSUE TITLE
Mock relevant part of crowd:it

### ISSUE THREAD

**Issue by corneliusottoleonard** [corneliusottoleonard/dscTeamLoewen#3]
Mock the calling of the predictions in Java for testing purposes.
[] ask Simon Brunner for the format of the Java object

**Comment by hm-gendress** [comment]
Add interfaces to convert csv files to java-objects with commit 6b3c22c2f54343168c9d07c4dff455fbf4265628

**Comment by hm-gendress** [comment]
Add interfaces to convert csv-files to java-objects with commit 6b3c22c2f54343168c9d07c4dff455fbf4265628

**Comment by hm-gendress** [comment]
Add java test classes and junit tests with commit cb56010ea7e03ceffcaa6db190bc4ada60a4dd7e

**Comment by Sebastianschmid1** [comment]
Code in paired programming tested and issue done

**Comment by Sebastianschmid1** [comment]
Code in paired programming tested and issue done
